name: 💡 Feature Request
description: Suggest a new idea or enhancement
title: "[FEATURE] - "
labels: [enhancement]
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        We welcome your ideas to improve this project! Share your feature request clearly.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What would you like to see added or changed?
      placeholder: "Add a dark mode switch for the UI"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain the benefit of this feature or the problem it solves.
      placeholder: "It would improve accessibility and reduce eye strain."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: Describe how you imagine the feature being implemented (optional).
      placeholder: "Use Tailwind dark mode classes and localStorage toggle."
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: How important is this feature?
      description: What level of impact would this feature have?
      options:
        - Must-have 🚀
        - Nice-to-have 👍
        - Just an idea 💭
    validations:
      required: true
